name: build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone mill
        run:
          git clone git@github.com:com-lihaoyi/mill.git /tmp/mill
      - name: Build local
        run:
          ./mill installLocal
        working-directory: /tmp/mill

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Compile
        env:
          MILL_DIR: /tmp/mill/target
        run:
          bash build/build.sh
